# Generated by Django 4.2.9 on 2024-01-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_members_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
